### ISSUE TITLE
Navbar has some odd spacing with the logo and menu button

### ISSUE THREAD

**Issue by ermsdev** [ASWWU-Web/ASWWU-Mask#89]
The ASWWU logo and menu button are shifted upward, sticky behavior hides part of the navbar on mobile while scrolling. These issues are not present on homepage, so they're most likely due to something in the mask repo not shared-ng.

![Screenshot_20191118-180733_Chrome](https://user-images.githubusercontent.com/10591356/69110057-5b9cd680-0a2e-11ea-890a-3fb28d9652d9.jpg)
![Screenshot_20191118-180714_Chrome](https://user-images.githubusercontent.com/10591356/69110062-5fc8f400-0a2e-11ea-8656-680f8257864d.jpg)

**Comment by nick97eagles** [comment]
Root of the issue could not be found. Going forward this issue should be put aside until mask is merged into frontend repo.

**Comment by nick97eagles** [comment]
This issue resolved itself when mask code was merged in with frontend.
