### ISSUE TITLE
super search results text is too dark to read

### ISSUE THREAD

**Issue by ermsdev** [ASWWU-Web/ASWWU-Mask#94]
<img width="1440" alt="Screen Shot 2019-11-18 at 11 12 51 PM" src="https://user-images.githubusercontent.com/10591356/69124548-032efe80-0a59-11ea-89c8-be63d5782796.png">

likely related to #93 though I thought search results were rendered in a shared component, so I'm not sure why the text is white on the home screen but dark gray on super search

**Comment by nick97eagles** [comment]
I fixed this issue in pull request #95
